// <auto-generated />
using System;
using EnerjiSA.GenerationService.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace EnerjiSA.GenerationService.Data.Migrations
{
    [DbContext(typeof(EnerjiSaContext))]
    [Migration("20210822153930_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityByDefaultColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("EnerjiSA.GenerationService.Entity.Entities.PowerPlant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .UseIdentityByDefaultColumn();

                    b.Property<string>("WebId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("WebId")
                        .IsUnique()
                        .HasDatabaseName("IX_WEBID");

                    b.ToTable("PowerPlant");
                });

            modelBuilder.Entity("EnerjiSA.GenerationService.Entity.Entities.PowerPlantData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .UseIdentityByDefaultColumn();

                    b.Property<bool?>("Good")
                        .HasColumnType("boolean");

                    b.Property<int>("PowerPlantId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PowerPlantId");

                    b.ToTable("PowerPlantData");
                });

            modelBuilder.Entity("EnerjiSA.GenerationService.Entity.Entities.PowerPlantData", b =>
                {
                    b.HasOne("EnerjiSA.GenerationService.Entity.Entities.PowerPlant", "PowerPlant")
                        .WithMany("PowerPlantDatas")
                        .HasForeignKey("PowerPlantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PowerPlant");
                });

            modelBuilder.Entity("EnerjiSA.GenerationService.Entity.Entities.PowerPlant", b =>
                {
                    b.Navigation("PowerPlantDatas");
                });
#pragma warning restore 612, 618
        }
    }
}
